config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get  'profile_edit/:id', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile_update/:id', to: 'users/registrations#profile_update', as: 'profile_update'
  end
  root 'jiros#index'
  resources :users

  resources :jiros do
    collection do
      match 'search' => 'jiros#search', via: [:get, :post]
    end
  end

  resources :favorites, only: [:create, :destroy]

  #いいね機能
  post '/favorite/:jiro_id' => 'favorites#like', as: 'like'
  delete '/favorite/:jiro_id' => 'favorites#unlike', as: 'unlike'
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :jiro, counter_cache: :favorites_count
  validates :user_id, {presence: true}
  validates :jiro_id, {presence: true}
  validates :jiro_id, uniqueness: {scope: :user_id}
end

app/controllers/favorites_controller.rb
# frozen_string_literal: true

class FavoritesController < ApplicationController
  before_action :set_variables, :authenticate_user!

  def like
    like = current_user.favorites.new(jiro_id: @jiro.id)
    like.save
  end

  def unlike
    like = current_user.favorites.find_by(jiro_id: @jiro.id)
    like.destroy
  end

    private

    def set_variables
      @jiro = Jiro.find(params[:jiro_id])
      @id_name = "#like-link-#{@jiro.id}"
    end

    # def current_user
    #   @current_user = @current_user || User.find_by(id: session[:user_id])
    # end


end

app/helpers/favorites_helper.rb
module FavoritesHelper

  def current_user?(user)
    user == current_user
  end

end

app/views/favorites/_favorite.html.erb
<div class="like-link" id="like-link-<%= jiro.id %>">
  <% if user_signed_in? && current_user.favorites.find_by(jiro_id: jiro.id) %>
     <%= link_to unlike_path(jiro.id), method: :delete, remote: true do %>
         <div class = "iine__button">❤️<%= jiro.favorites.count %></div>
     <% end %>
   <% else %>
     <%= link_to like_path(jiro.id), method: :post, remote: true do %>
         <div class = "iine__button">♡️<%= jiro.favorites.count %></div>
     <% end %>
   <% end %>
</div>

app/views/favorites/like.js.erb
$("<%= @id_name %>").html('<%= j(render partial: "favorites/favorite", locals: { jiro: @jiro } ) %>');

app/views/favorites/unlike.js.erb
$("<%= @id_name %>").html('<%= j(render partial: "favorites/favorite", locals: { jiro: @jiro } ) %>');