config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get  'profile_edit/:id', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile_update/:id', to: 'users/registrations#profile_update', as: 'profile_update'
  end
  root 'jiros#index'
  resources :users

  resources :jiros do
    collection do
      match 'search' => 'jiros#search', via: [:get, :post]
    end
  end

  resources :favorites, only: [:create, :destroy]

  #いいね機能
  post '/favorite/:jiro_id' => 'favorites#like', as: 'like'
  delete '/favorite/:jiro_id' => 'favorites#unlike', as: 'unlike'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :profile_picture, ImageUploader
  validate :picture_size
  has_many :jiros, dependent: :destroy

  #いいね機能
  has_many :favorites, dependent: :destroy
  has_many :like_jiros, through: :favorites, source: :jiro

  private


  # アップロードされた画像のサイズをバリデーションする
  def picture_size
    if profile_picture.size > 5.megabytes
      errors.add(:profile_picture, "should be less than 5MB")
    end
  end

  def current_user?(user)
    user == current_user
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
   before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
   def profile_edit
     @user = User.find(params[:id])
   end

  # PUT /resource
   def profile_update
     @user = User.find(params[:id])
     @user.assign_attributes(user_params)
     if @user.save
       flash[:notice] = "プロフィールを更新しました"
       redirect_to @user
     else
       render "profile_edit"
     end
   end

   private
     #ストロングパラメーター
     def user_params
       params.require(:user).permit(:name, :profile_picture, :introduction)
     end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile_picture, :introduction])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    if user_session.delete
      redirect_to new_user_session_path, notice: "ログアウトしました"
    end
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :show]

    # if params[:q] == { sorts: 'updated_at_desc' }
    #   #検索フォームからアクセスしたときの処理
    #   @q = Jiro.ransack(search_params)
    #   @search = @q.result
    #   @jiros = Jiro.all
    #   @jiros = Jiro.page(params[:page]).per(8).order(created_at: :desc)
    # elsif params[:q] == { sorts: 'favorites_count_desc' }
    #   #検索フォーム以外からアクセスしたときの処理
    #   @q = Jiro.ransack()
    #   @jiros = Jiro.all
    #   @jiros = Jiro.page(params[:page]).per(8).order(favorites_count: :desc)

    # end
  # end

  def new
  end

  def edit
    # @user = @user || User.find_by(id: session[:user_id])
    @user = current_user
  end

  def show
    # @user = @user || User.find_by(id: session[:user_id])
    @user = current_user
    # @jiros = Jiro.all
    @jiros = Jiro.where(user_id: current_user.id)
    @jiros = Kaminari.paginate_array(@jiros).page(params[:page]).per(8)
    @j = current_user.favorites.select("jiro_id")
    @favorites = Jiro.where(id: @j)
    @favorites = Kaminari.paginate_array(@favorites).page(params[:page]).per(8)
  end

  #   if params[:hoge] == 1
  #     @jiros = Jiro.all
  #     @jiros = Jiro.page(params[:page]).per(8).order(created_at: :desc)
  #   elsif params[:hoge] == 2
  #     @jiros = Jiro.all
  #     @jiros = Jiro.page(params[:page]).per(8).order(favorites_count: :desc)
  #   end
  #     redirect_to 'users/search'
  # end
    # end
    # if params[:q].present?
    #   #検索フォームからアクセスしたときの処理
    #   @search = Jiro.ransack(search_params)
    #   @jiros = @search.result
    # else
    #   params[:q] = { sorts: 'id desc' }
    #   @search = Jiro.ransack()
    #   @jiros = Jiro.all
    # end
  # end



  private
    #ストロングパラメーター
    def user_params
      params.require(:user).permit(:name, :email, :profile_picture, :password, :password_confirmation, :introduce)
    end


    def search_params
      params.require(:q).permit(:sorts)
    end


end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper

end

app/views/users/_new.html.erb
<li class="nav-item">
  <%= link_to "お気に入り", user_path, {id: "okiniiri", class: "nav-link", remote: true} %>
  <!-- <div id="okiniiri" class="nav-link" data-toggle="tab"></div> -->
  <!-- <a href="#okiniiri" class="nav-link" data-toggle="tab">お気に入り</a> -->
</li>

app/views/users/search.html.erb
<!-- <head> -->

  <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
  <!-- <meta name="description" content="">
  <meta name="author" content=""> -->

<!-- </head> -->

  <div class="top-page-container">
<h1>みんなの投稿</h1>
<%= form_tag(search_users_path, method: "get") do %>
  <%= select_tag :hoge, options_for_select([["並び替え", "0"],["新着順", "1"], ["いいね順", "2"]]) %>
  <%= submit_tag "絞り込み" %>
<% end %>
<!-- <div class="search_field">
</div> -->
    <!-- Page Features -->
    <div class="row text-center">

    <% @jiros.each do |jiro| %>
      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card-body">

        <%= link_to jiro, class: "card" do %>
          <%= image_tag jiro.picture.url, :size => '245x200' %>
            <h4 class="card-title">
              <% if jiro.store_id %>
                <%= Store.find_by_id(jiro.store_id)&.name %>
              <% else %>
                <%= "店舗情報なし" %>
              <% end %>
            </h4>
            <!-- <div class="card-footer"> -->
            <!-- </div> -->

          <!-- </div> -->
          <% end %>
          <%= render partial: 'jiros/jiros', locals: { jiro: jiro } %>
        </div>
        </div>
    <% end %>

  </div>

    <!-- <div class="row text-center"> -->
      <%= paginate @jiros %>
    <!-- </div> -->


  </div>

app/views/users/show.html.erb
<div class="container">
  <div class="row align-items-center justify-content-center">
    <aside class="col-md-6">
      <section class="user_info">
        <h1>
          <% if @user.profile_picture? %>
            <%= image_tag (@user.profile_picture.url) %>
          <% else %>
            <%= image_tag "/assets/default.jpg", :size => '250x250' %>
          <% end %>
          <%= @user.name %>
        </h1>
      </section>
    </aside>
    <aside class="col-md-6">
      <%= button_to 'プロフィール編集', profile_edit_path, method: :get, class: "btn btn-primary btn-outline-primary btn-round" %>
    </aside>
  </div>

  <div class="row align-items-center justify-content-center">
    <aside class="col-md-12">
      <span class="introduction"><%= @user.introduction %></span>
    </aside>
  </div>

  <hr width="100%">

  <div class="row select-bar align-items-center justify-content-center">
    <aside class="col-md-12 select-bar">
      <ul class="nav nav-pills nav-justified">
        <li class="nav-item">
          <a href="#toukou" class="nav-link active" data-toggle="tab">自分の投稿</a>
        </li>
        <li class="nav-item">
          <a href="#okiniiri" class="nav-link" data-toggle="tab">お気に入り</a>
        </li>
      </ul>

      <div class="tab-content">
        <div class="tab-pane active" id="toukou">
          <div class="row text-center">
          <% @jiros.each do |jiro| %>
            <div class="col-lg-3 col-md-6 mb-4">
              <div class="card-body">
              <%= link_to jiro, class: "card" do %>
                <%= image_tag jiro.picture.url, :size => '245x200' %>
                  <h4 class="card-title">
                    <% if jiro.store_id %>
                      <%= Store.find_by_id(jiro.store_id)&.name %>
                    <% else %>
                      <%= "店舗情報なし" %>
                    <% end %>
                  </h4>
                <% end %>
                <%= render partial: 'jiros/jiros', locals: { jiro: jiro } %>
              </div>
              </div>
          <% end %>
        </div>
          <%= paginate @jiros %>
        </div>

        <div class="tab-pane" id="okiniiri">
          <!-- <div class="tab-pane active" id="toukou"> -->
            <div class="row text-center">
            <% @favorites.each do |jiro| %>
              <div class="col-lg-3 col-md-6 mb-4">
                <div class="card-body">
                <%= link_to jiro, class: "card" do %>
                  <%= image_tag jiro.picture.url, :size => '245x200' %>
                    <h4 class="card-title">
                      <% if jiro.store_id %>
                        <%= Store.find_by_id(jiro.store_id)&.name %>
                      <% else %>
                        <%= "店舗情報なし" %>
                      <% end %>
                    </h4>
                  <% end %>
                  <%= render partial: 'jiros/jiros', locals: { jiro: jiro } %>
                </div>
                </div>
            <% end %>
          </div>
            <%= paginate @favorites %>
          </div>
      </div>
    </aside>
  </div>
</div>

app/views/users/show.js.erb
$('#okiniiri').html("<%= escape_javascript(render 'user') %>");