config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get  'profile_edit/:id', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile_update/:id', to: 'users/registrations#profile_update', as: 'profile_update'
  end
  root 'jiros#index'
  resources :users

  resources :jiros do
    collection do
      match 'search' => 'jiros#search', via: [:get, :post]
    end
  end

  resources :favorites, only: [:create, :destroy]

  #いいね機能
  post '/favorite/:jiro_id' => 'favorites#like', as: 'like'
  delete '/favorite/:jiro_id' => 'favorites#unlike', as: 'unlike'
end

app/views/shared/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="footer py-3 bg-dark">
    <p class="m-0 text-center text-white">©ジロログ製作委員会</p>
  <!-- /.container -->
</footer>

app/views/shared/_header.html.erb
<header>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <%= link_to 'ジロログ', root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
              <span class="sr-only">(current)</span>
          </li>
          <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" href="#">店舗で絞る</a>
          </li>
          <li class="nav-item">
            <%= link_to '投稿する', new_jiro_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'マイページ', current_user, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <% else %>
          <li class="nav-item">
            <a class="nav-link" href="#">お店を探す</a>
          </li>
          <li class="nav-item">
            <%= link_to 'ログイン', new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to '会員登録', new_user_registration_path, class: "nav-link" %>
          </li>

          <% end %>
        </ul>
      </div>
    </div>
  </nav>


</header>