config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get  'profile_edit/:id', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile_update/:id', to: 'users/registrations#profile_update', as: 'profile_update'
  end
  root 'jiros#index'
  resources :users

  resources :jiros do
    collection do
      match 'search' => 'jiros#search', via: [:get, :post]
    end
  end

  resources :favorites, only: [:create, :destroy]

  #いいね機能
  post '/favorite/:jiro_id' => 'favorites#like', as: 'like'
  delete '/favorite/:jiro_id' => 'favorites#unlike', as: 'unlike'
end

app/models/jiro.rb
class Jiro < ApplicationRecord
  belongs_to :user
  belongs_to :store
  mount_uploader :picture, ImageUploader
  has_many :favorites, dependent: :destroy
  has_many :liking_users, through: :favorites, source: :user




end

app/controllers/jiros_controller.rb
class JirosController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def index
      # if params[:option] == "A" || params[:option] == nil
      #   @jiros = Jiro.all.order('created_at DESC')
      # elsif params[:option] == "B"
      #   @jiros = Jiros.all.order('created_at ASC')
      # end
      @jiros = Jiro.all
      @jiros = Jiro.page(params[:page]).per(8).order(created_at: :desc)

      # @jiros_rank = Jiro.all.order(favorites_count: "DESC")
      # @user = @user || User.find_by(id: session[:user_id])
      @user = current_user

      @q = Jiro.ransack(params[:q])
      @jiross = @q.result(distinct: true)
  end

  def show
    @jiro = Jiro.find(params[:id])
    @poster  = User.find_by(id: @jiro.user_id)
    @store = Store.find_by(id: @jiro.store_id)
  end

  def new
    @jiro = Jiro.new
  end


  def create
    @user = current_user
    @jiro = @user.jiros.build(jiro_params)
    if @jiro.save
      flash[:success] = "投稿しました"
      redirect_to @user
    else
      render "jiros/new"
    end
  end

  def search
    @jiros = Jiro.all
    @jiros = Jiro.page(params[:page]).per(8).order(created_at: :desc)

    if params[:hoge] == "1"
      @jiros = Jiro.all
      @jiros = Jiro.page(params[:page]).per(8).order(created_at: :desc)
    elsif params[:hoge] == "2"
      @jiros = Jiro.all
      @jiros = Jiro.page(params[:page]).per(8).order(favorites_count: :desc)
    end

    if params[:q].present?
      #検索フォームからアクセスしたときの処理
      @q = Jiro.ransack(params[:q])
      @result = @q.result(distinct: true).page(params[:page]).per(8)
    else
      @q = Jiro.ransack(search_params)
      @result = @q.result(distinct: true)
    end
  end
    # render :index

  # def search
  #   if params[:q].present?
  #     #検索フォームからアクセスしたときの処理
  #     @search = Jiro.ransack(search_params)
  #     @jiros = @search.result
  #   else
  #     params[:q] = { sorts: 'id desc' }
  #     @search = Jiro.ransack()
  #     @jiros = Jiro.all
  #   end
  # end

  private
    #ストロングパラメーター
    def jiro_params
      params.require(:jiro).permit(:picture, :store_id, :weather, :date, :waiting_time, :call, :pork, :soup, :comment, :favorites_count)
    end

    def search_params
      params.require(:q).permit(:name_cont)
    end

end

app/helpers/jiros_helper.rb
module JirosHelper
end

app/views/jiros/_jiros.html.erb
<%= render 'favorites/favorite', jiro: jiro %>

app/views/jiros/index.html.erb
<!-- <head> -->

  <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
  <!-- <meta name="description" content="">
  <meta name="author" content=""> -->

<!-- </head> -->

  <div class="top-page-container">
<h1>みんなの投稿</h1>

<%= form_tag(search_jiros_path, method: "get") do %>
  <%= select_tag :hoge, options_for_select([["新着順", "1"], ["いいね順", "2"]]) %>
  <%= submit_tag "並び替え" %>
<% end %>
<!-- <div class="search_field">
</div> -->
    <!-- Page Features -->
    <div class="row text-center">

    <% @jiros.each do |jiro| %>
      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card-body">

        <%= link_to jiro, class: "card" do %>
          <%= image_tag jiro.picture.url, :size => '245x200' %>
            <h4 class="card-title">
              <% if jiro.store_id %>
                <%= Store.find_by_id(jiro.store_id)&.name %>
              <% else %>
                <%= "店舗情報なし" %>
              <% end %>
            </h4>
            <!-- <div class="card-footer"> -->
            <!-- </div> -->

          <!-- </div> -->
          <% end %>
          <%= render partial: 'jiros/jiros', locals: { jiro: jiro } %>
        </div>
        </div>
    <% end %>

  </div>

    <!-- <div class="row text-center"> -->
      <%= paginate @jiros %>
    <!-- </div> -->


  </div>

app/views/jiros/new.html.erb
<div class="container">
  <h2>二郎を投稿する</h2>
  <%= form_for @jiro do |f| %>
  <div class="row align-items-center justify-content-center">
    <aside class="col-md-12">
      <div class="view_box">
        <% if @jiro.picture? %>
          <%= image_tag @jiro.picture_url, :size => '400x400' %>
        <% else %>
          <%= image_tag "/assets/ramen2.jpg", :size => '400x400' %>
        <% end %>
      <button type="button" class="btn btn-outline-secondary rounded-pill img-button">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: 'file',　autofocus: true, required: true %>
      </button>
      </div>
    </aside>
  </div>

  <div class="row align-items-center justify-content-center">
    <aside class="col-md-8">
      <table class="table">
      <div class="form-group">
        <%= f.label '店舗' %><br />
        <div class="input-form">
        <%= f.select :store_id, [ ["三田本店",1], ["目黒店", 2], ["仙川店", 3 ] ,["新宿歌舞伎町店", 4], ["品川店", 5], ["新宿小滝橋通り店", 6], ["環七新新代田店", 7], ["八王子野猿街道店２", 8 ] ,["池袋東口店", 9], ["亀戸店", 10], ["京急川崎店", 11], ["府中店", 12], ["松戸駅前店", 13 ] ,["めじろ台店", 14], ["荻窪店", 15], ["上野毛店", 16], ["京成大久保店", 17], ["環七一之江店", 18] ,["相模大野店", 19], ["横浜関内店", 20], ["神田神保町店", 21], ["小岩店", 22], ["ひばりヶ丘駅前店", 23 ] ,["桜台駅前店", 24], ["栃木街道店", 25], ["立川店", 26], ["千住大橋店", 27], ["茨城守谷店", 28] ,["湘南藤沢店", 29], ["西台駅前店", 30], ["中山駅前店", 31], ["仙台店", 32], ["札幌店", 33] ,["会津若松駅前店", 34], ["新潟店", 35], ["川越店", 36], ["京都店", 37], ["越谷店", 38] ,["前橋千代田町店", 39] ], prompt: "店舗を選択してください", :required => true %><br />
      </div>
      </div>
      <div class="form-group">
        <%= f.label '訪問日時' %><br />
        <div class="input-form">
        <%= f.datetime_select :date,
                          # autofocus: true,
                          default: Date.today + 12.hour,
                          class: 'form-control',
                          required: true %><br />
      </div>
      </div>
      <div class="form-group">
        <%= f.label '天気' %><br />
      <div class="input-form">
        <span style="margin-right: 3em;"><%= f.radio_button :weather, "雨", required: true %>雨</span>
        <span style="margin-right: 3em;"><%= f.radio_button :weather, "くもり", required: true %>くもり</span>
        <span style="margin-right: 3em;"><%= f.radio_button :weather, "晴れ", required: true %>晴れ<br /></span>
      </div>
      </div>
      <div class="form-group">
        <%= f.label '並び時間' %><br />
        <div class="select-form">
        <%= f.time_select :waiting_time,
                          # autofocus: true,
                          :default => {:hour => '00', :minute => '00'},
                          class: 'form-control',
                          required: true %><br />
      </div>
      </div>
      <div class="form-group">
        <%= f.label 'コール' %>
        <div class="input-form">
        <%= f.text_field :call,
                          # autofocus: true,
                          autocomplete: 'call',
                          class: 'form-control',
                          required: true,
                          maxlength: '30'%><br />
      </div>
      </div>
      <div class="form-group">
        <%= f.label '豚' %><br />
        <div class="input-form">
        <span style="margin-right: 3em;"><%= f.radio_button :pork, "パサ豚", required: true %>パサ豚</span>
        <span style="margin-right: 3em;"><%= f.radio_button :pork, "バランス豚", required: true %>バランス豚</span>
        <span style="margin-right: 3em;"><%= f.radio_button :pork, "神豚", required: true %>神豚</span><br />
      </div>
      </div>
      <div class="form-group">
        <%= f.label 'スープ' %><br />
        <div class="input-form">
        <span style="margin-right: 3em;"><%= f.radio_button :soup, "非乳化スープ", required: true %>非乳化スープ</span>
        <span style="margin-right: 3em;"><%= f.radio_button :soup, "バランススープ", required: true %>バランススープ</span>
        <span style="margin-right: 3em;"><%= f.radio_button :soup, "乳化スープ", required: true %>乳化スープ</span><br />
      </div>
      </div>
      <div class="form-group">
        <%= f.label '自由記入' %>
        <%= f.text_area :comment,
                        # autofocus: true,
                        class: 'form-control',
                        maxlength: '255'%><br />
      </div>
      </table>
      <div class="form-group"><br />
        <%= f.submit "投稿する", class: 'btn btn-primary btn-block' %>
      </div>
    </aside>
  </div>
  <% end %>


</div>

app/views/jiros/search.html.erb
<!-- <head> -->

  <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
  <!-- <meta name="description" content="">
  <meta name="author" content=""> -->

<!-- </head> -->

  <div class="top-page-container">
<h1>みんなの投稿</h1>
<%= search_form_for(@q, url:search_jiros_path, method: "get") do |f| %>
    <%= f.label :call_cont %>
    <%= f.search_field :call_cont %>
    <%= f.submit %>
<% end %>

<%= form_tag(search_jiros_path, method: "get") do %>
  <%= select_tag :hoge, options_for_select([["新着順", "1"], ["いいね順", "2"]]) %>
  <%= submit_tag "絞り込み" %>
<% end %>
<!-- <div class="search_field">
</div> -->
    <!-- Page Features -->
    <div class="row text-center">

    <% @result.each do |jiro| %>
      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card-body">

        <%= link_to jiro, class: "card" do %>
          <%= image_tag jiro.picture.url, :size => '245x200' %>
            <h4 class="card-title">
              <% if jiro.store_id %>
                <%= Store.find_by_id(jiro.store_id)&.name %>
              <% else %>
                <%= "店舗情報なし" %>
              <% end %>
            </h4>
            <!-- <div class="card-footer"> -->
            <!-- </div> -->

          <!-- </div> -->
          <% end %>
          <%= render partial: 'jiros/jiros', locals: { jiro: jiro } %>
        </div>
        </div>
    <% end %>

  </div>

    <!-- <div class="row text-center"> -->
      <%= paginate @result %>
    <!-- </div> -->


  </div>

app/views/jiros/show.html.erb
<div class="container">
  <%= form_for @jiro do |f| %>
  <div class="row align-items-center justify-content-center">
    <aside class="col-md-12">
      <div class="view_box">
        <% if @jiro.picture? %>
          <%= image_tag @jiro.picture.url %>
        <% else %>
          <%= image_tag "/assets/ramen.jpg", :size => '400x400' %>
        <% end %>
      </div>
      <% end %>
<div class="table-container">
  <table>
  <tr>
    <th>投稿者</th>
    <td><%= @poster.name %></td>
  </tr>
  <tr>
    <th>店舗</th>
    <td><%= @store.name %></td>
  </tr>
  <tr>
    <th>訪問日時</th>
    <td><%= @jiro.date.strftime("%Y年%m月%d日%H時%M分") %></td>
  </tr>
  <tr>
    <th>並び時間</th>
    <td><%= @jiro.waiting_time.strftime("%-H時間%M分") %></td>
  </tr>
  <tr>
    <th>天気</th>
    <td><%= @jiro.weather %></td>
  </tr>
  <tr>
    <th>コール</th>
    <td><%= @jiro.call %></td>
  </tr>
  <tr>
    <th>スープ</th>
    <td><%= @jiro.soup %></td>
  </tr>
  <tr>
    <th>豚</th>
    <td><%= @jiro.pork %></td>
  </tr>
  <tr>
    <th>感想</th>
    <td><%= @jiro.comment %></td>
  </tr>

</table>
</div>
</aside>
</div>
</div>